"""Offline test for the Confluence space-export importer.

Builds a tiny synthetic export (one real page with chrome + table + list, one
stub page) and asserts the conversion: title extraction, chrome stripping,
markdown structure, stub skipping, and slug collision handling.

Run directly:        python tests/test_confluence.py
Or under pytest:     pytest tests/test_confluence.py
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from atlantis.confluence import convert_page, import_space_export  # noqa: E402

PAGE = """<!DOCTYPE html>
<html><head><title>Demo Space : Billing Overview</title></head>
<body>
<div id="page">
  <div id="breadcrumb-section"><ol id="breadcrumbs"><li>Demo Space</li></ol></div>
  <div id="content">
    <div class="page-metadata">Created by Someone on Jan 01, 2026</div>
    <div id="main-content">
      <h1>How billing works</h1>
      <p>Invoices are generated on the <strong>first</strong> of each month.</p>
      <ul><li>Net-30 terms</li><li>ACH or card</li></ul>
      <table><tr><th>Plan</th><th>Price</th></tr>
      <tr><td>Basic</td><td>$10</td></tr>
      <tr><td>Pro | Plus</td><td>$25</td></tr></table>
      <p>See <a href="https://example.com/docs">the docs</a> and
         <a href="Other-Page_123.html">the other page</a>.</p>
      <div class="pageSection group"><h2>Attachments:</h2><p>img.png</p></div>
    </div>
  </div>
  <div id="footer"><p>Document generated by Confluence on Jan 02, 2026</p></div>
</div>
</body></html>"""

STUB = """<html><head><title>Demo Space : Empty Stub</title></head>
<body><div id="main-content"><p>Nothing here.</p></div></body></html>"""


def test_convert_page_extracts_and_strips():
    title, body = convert_page(PAGE)
    assert title == "Billing Overview"
    # Content survived, structured.
    assert "# How billing works" in body
    assert "**first**" in body
    assert "- Net-30 terms" in body
    assert "| Plan | Price |" in body
    assert "| Pro \\| Plus | $25 |" in body
    # External links keep URLs; intra-export links keep only their label.
    assert "[the docs](https://example.com/docs)" in body
    assert "the other page" in body and "Other-Page_123.html" not in body
    # Chrome is gone.
    for chrome in ("Created by Someone", "Document generated by Confluence",
                   "Attachments:", "breadcrumbs"):
        assert chrome not in body, chrome


def test_import_space_export_writes_skips_and_dedupes():
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        export = tmp / "export" / "SPACE"
        export.mkdir(parents=True)
        (export / "Billing-Overview_1.html").write_text(PAGE, encoding="utf-8")
        # Same title again -> slug collision -> suffixed file, not overwrite.
        (export / "Billing-Overview_2.html").write_text(PAGE, encoding="utf-8")
        (export / "Empty-Stub_3.html").write_text(STUB, encoding="utf-8")
        # Chrome dirs are never scanned for pages.
        (export / "attachments").mkdir()
        (export / "attachments" / "not-a-page.html").write_text(PAGE, encoding="utf-8")

        out = tmp / "raw"
        report = import_space_export(tmp / "export", out, min_words=10)

        assert report.converted == 2
        assert report.skipped_stubs == 1
        names = sorted(p.name for p in out.glob("*.md"))
        assert names == ["billing-overview-2.md", "billing-overview.md"]
        text = (out / "billing-overview.md").read_text(encoding="utf-8")
        # H1 title first, so `discover` reads it back as the document title.
        assert text.startswith("# Billing Overview\n")


if __name__ == "__main__":
    test_convert_page_extracts_and_strips()
    test_import_space_export_writes_skips_and_dedupes()
    print("OK: all confluence import tests passed")
